# Generated by Django 4.1.7 on 2023-02-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_alter_kit_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='shop/images'),
        ),
    ]
