# Generated by Django 4.1.7 on 2023-02-22 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_productentry_description_alter_order_kit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productentry',
            old_name='quantity',
            new_name='quantity_product',
        ),
        migrations.AddField(
            model_name='productentry',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productentry',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
