# Generated by Django 4.1.7 on 2023-02-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_quantity_productentry_quantity_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
