# Generated by Django 4.1.7 on 2023-02-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_kit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='shop/images'),
        ),
    ]
