# Generated by Django 4.1.7 on 2023-02-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='stock_kit',
            field=models.IntegerField(),
        ),
    ]
