# Generated by Django 4.1.7 on 2023-02-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_alter_kit_stock_kit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_product',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
